### ISSUE TITLE
About the code of MS-LapSRN model 

### ISSUE THREAD

**Issue by zhgqcn** [lorenzomammana/MSLapSRN-pytorch#1]
Thanks for your repository which helps my learn the model . However , I have some questions about the code are as following:
```
 features = features[:, :, :-1, :-1]
 rescaled_img = self.scale_img(rescaled_img)
 rescaled_img = rescaled_img[:, :, 1:-1, 1:-1]
```
why the start index of slice of features is from 0, and the rescaled_image is from 1?
**And why should cut the slice, can we add them directly.**
```
 features = features[:, :, :, :]
 rescaled_img = self.scale_img(rescaled_img)
 rescaled_img = rescaled_img[:, :, :, :]
```

**Comment by lorenzomammana** [comment]
This is something that has bothered me too, to be honest, these are the exact same steps used in the original matlab code https://github.com/phoenix104104/LapSRN/blob/master/init_MSLapSRN_model.m , I remember taking quite a bit of time to analyze the reason of the crop but never found a solution...

To be honest I don't think anything is going to change if you use your version, if you have time you could give it a try 👍.

**Comment by zhgqcn** [comment]
Thank you for your answer. I think this is because of the dataset, most models used the famous datasets like SET5, BSDS500. And We can find the width and height of these datasets are different.  
Yes , because of my own datasets is square image, I have made my try and get good results.
```python
    def forward(self, x):
        
        features_x2 = self.conv_input(x)                                # in:3   out:64
        features_x2 = self.features(features_x2)                        # in:64  out:64
        features_x2 = self.transpose(self.relu_features(features_x2))   # in:64  out:64
        predict_x2 = self.predict(features_x2)                          # in:64  out:3

        # rescaled_img_x2 = x.clone()                                     # 3 channels
        rescaled_img_x2 = self.scale_img(x)               # in:3  out:1
        
        out_2 = predict_x2 + rescaled_img_x2                  # 3 channels 
        

        features_x4 = self.conv_input(out_2)                            # in:3   out:64
        features_x4 = self.features(features_x4)                        # in:64  out:64
        features_x4 = self.transpose(self.relu_features(features_x4))   # in:64  out:64
        predict_x4 = self.predict(features_x4)                          # in:64  out:3

        # rescaled_img_x4 = out_2.clone()                                 # 3 channels
        rescaled_img_x4 = self.scale_img(out_2)                           # in:3  out:1
        
        out_4 = predict_x4 + rescaled_img_x4                              # 3 channels 
        
        return out_2, out_4
```

**Comment by anandhiray** [comment]
I am trying to run this  in kaggle and I am getting the error.

 File "/kaggle/working/MSLapSRN-pytorch/SRdataset.py", line 54, in __getitem__
     id = self.list_ids[int(self.true_len * index / self.__len__())]
IndexError: list index out of range.

I have tried several modifications and it is still not working. Can you please help me?
