### ISSUE TITLE
SRdataset.py is giving error

### ISSUE THREAD

**Issue by anandhiray** [lorenzomammana/MSLapSRN-pytorch#3]
I am trying to run this  in kaggle and I am getting the error.

 File "/kaggle/working/MSLapSRN-pytorch/SRdataset.py", line 54, in __getitem__
   id = self.list_ids[int(self.true_len * index / self.__len__())]
IndexError: list index out of range.

I have tried several modifications and it is still not working. Can you please help me?

**Comment by lorenzomammana** [comment]
Are you sure that the data is in the correct location and loaded properly? I've checked the code and it seems to me that this error could only appear if your list_ids is empty.

The dataset is loaded through
self.list_ids = glob.glob('dataset/{}/*.png'.format(settype))

Maybe your images are not .png? 
To double check I would try to print out the content of list_ids

**Comment by anandhiray** [comment]
Thank you!
